apiVersion: v1
kind: Pod
metadata:
  name: arena-launcher-job
  namespace: kube-system
spec:
  serviceAccountName: admin
  restartPolicy: Never
  hostNetwork: true
  containers:
  - command: 
    - python
    - arena_launcher.py
    args:
    - --name
    - download-data
    - --data
    - "training:/training"
    - --image
    - byrnedo/alpine-curl
    - job
    - --
    - "mkdir -p /training/dataset/mnist && \
  cd /training/dataset/mnist && \
  curl -O https://code.aliyun.com/xiaozhou/tensorflow-sample-code/raw/master/data/t10k-images-idx3-ubyte.gz && \
  curl -O https://code.aliyun.com/xiaozhou/tensorflow-sample-code/raw/master/data/t10k-labels-idx1-ubyte.gz && \
  curl -O https://code.aliyun.com/xiaozhou/tensorflow-sample-code/raw/master/data/train-images-idx3-ubyte.gz && \
  curl -O https://code.aliyun.com/xiaozhou/tensorflow-sample-code/raw/master/data/train-labels-idx1-ubyte.gz"
    image: cheyang/arena_launcher
    imagePullPolicy: Always
    name: arena-launcher